Rspec
Ashah15/Enumerables-methods pull request #2
Opened 2019-09-17 21:05 UTC by jucora

Thanks for code review

2019-09-17 22:49 UTC, maelfosso requested changes
Hello @jucora @Ashah15 

# :clap:  Thank for that beautiful RSPEC code :smile: 

The test all passed. But before moving forward there some changes you have to make.

- [x] Please use `require_relative` instead of `require`

- [x] Write the test by comparing the result not with a constant value but with the result of the original method
**For example** instead of writing
```ruby
expect(test_array.my_all? do |x| x % 2 == 0 end).to eq(true)
```
Write
```
expect(test_array.my_all? do |x| x % 2 == 0 end).to eq(test_array.all? do |x| x % 2 == 0 end)
```
- [x] Some methods like `my_all?`, `my_any?`, `my_count`, `my_inject` need more than just one test because there is a lot of use case. For example, **my_count**, there is a use case without an argument and another one with the block. So Please complete.

Kindly, make the suggested change and re-submit a new code review request.
Thanks

2019-09-17 22:49 UTC, maelfosso commented on spec/my_methods_spec.rb
> +require '../my_methods'
**`REQUIRED`** Please use `require_relative`

2019-09-18 16:56 UTC, jucora commented
Thanks for code review, it was helpful

Now methods receive arguments and more tests were added and also all the expects for every test is compared with the result of the original method.

Thanks

2019-09-18 20:27 UTC, samgaco approved these changes
Hi @Ashah15 and @jucora :high_brightness: 

Good job team :100: the project is approved, you may merge now to the master branch and submit the project completion form.

------------------

And remember :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description


----------------


* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-18 20:27 UTC, samgaco commented on spec/my_methods_spec.rb
> +require_relative '../my_methods'
:+1:

2019-09-18 20:27 UTC, samgaco commented on spec/my_methods_spec.rb
> +      expect(test_array_1.my_each { |element| element }).to eql(test_array_1.each { |element| element })
Well done, like this you are testing against the methods you are trying to emulate :100: :white_check_mark:

2019-09-18 20:40 UTC, merged